# ~/.bash_profile ou ~/.zprofile
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    exec Hyprland
fi

# Keyring (silencioso, só se ainda não estiver ativo)
[ -n "$GNOME_KEYRING_CONTROL" ] || eval "$(gnome-keyring-daemon --start --components=secrets,ssh,pkcs11 2>/dev/null)"
