# Hyprland só no TTY1
if [[ -z $DISPLAY && $(tty) = /dev/tty1 ]]; then
  exec start-hyprland
fi
# gnome-keyring silencioso e idempotente
[ -n "$GNOME_KEYRING_CONTROL" ] || eval "$(gnome-keyring-daemon --start --components=secrets,ssh,pkcs11 2>/dev/null)"
