hl.on("hyprland.start", function()
    hl.exec_cmd("swaync")
    hl.exec_cmd("sleep 1; swaync-client --dnd-off")
    hl.exec_cmd("sleep 1; $HOME/.config/hypr/scripts/swaync-fullscreen-dnd.sh")
    hl.exec_cmd("mkdir -p $HOME/.local/state/waybar; waybar -l info -b hyprland >>$HOME/.local/state/waybar/waybar.log 2>&1")
    hl.exec_cmd("env -u QT_QPA_PLATFORM steam -silent")
    hl.exec_cmd("copyq")
    hl.exec_cmd("sleep 2; WHATSAPP_START_HIDDEN=1 $HOME/.local/bin/whatsapp-web-chromium")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("sleep 1; $HOME/.config/hypr/scripts/hyprpaper_change.sh")
    hl.exec_cmd("sleep 0.3; $HOME/.config/hypr/scripts/waybar-hover-daemon.sh")
    hl.exec_cmd("hyprctl setcursor rose-pine-hyprcursor 32")
    hl.exec_cmd("udiskie --tray")
    hl.exec_cmd("kbuildsycoca6 --noincremental")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE")
    hl.exec_cmd("razer-cli --dpi 800")
end)
